### ISSUE TITLE
Add a License to make it Open Source?

### ISSUE THREAD

**Issue by maxhbr** [sebastian-stumpf/uninarf#1]
Hey @sebastian-stumpf,

I like your project!

I am surprised, that it is lacking a license. Maybe add a 
* "CERN Open Hardware Licence Version 2 - Permissive" similar to https://github.com/GEIGEIGEIST/TOTEM/blob/main/LICENSE.md or 
* a MIT similar to https://gitlab.com/lpgalaxy/revxlp/-/blob/main/LICENSE.

This would allow others to use and improve upon your project.

**Comment by sebastian-stumpf** [comment]
I always forget about that part. Thank you. I've added the file in d3b0e8a95882a9c888a97ceea45f484f63d3ae67.
