### ISSUE TITLE
Keycaps

### ISSUE THREAD

**Issue by jurica** [sebastian-stumpf/uninarf#2]
Hi Sebastian,

I wonder what keycaps you are using on this picture: https://github.com/sebastian-stumpf/uninarf/blob/master/pictures/uninarf.jpg
It looks like the first and third row is tilted, but as far as I can tell from the picture the switches are mounted flush.
Would you mind uploading some more pictures of that board or explain how you reached that?

Thanks in advance!
Juri

PS: Sorry for opening an issue for that question but I haven't found any other way contacting you.

**Comment by sebastian-stumpf** [comment]
They are mounted via these keycap tilters: https://www.printables.com/model/197363-choc-keycap-tilter

**Comment by jurica** [comment]
Thank you for your response!
